version: "3.3"
services:
  app:
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    ports:
      - 8080:8080
    command: sh -c "yarn && yarn serve"
